@startuml Funtional_requirements
left to right direction


Player <|-- Lobby_Creator

rectangle Lobby {
  usecase "Join lobby" as L_UC1
  usecase "Create lobby" as L_UC2
  usecase "Change name" as L_UC3
  usecase "Manage players" as L_UC4
  usecase "Start game" as L_UC5
}

rectangle SKBD_Memory {
  usecase "Select cards" as UC1
  usecase "Get shown drink" as UC2
}

Player --> L_UC1
Lobby_Creator --> L_UC2
Lobby_Creator --> L_UC3
Lobby_Creator --> L_UC4
Lobby_Creator --> L_UC5

Player --> UC1
Player --> UC2


@enduml